manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/petejohanson
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: zephyr-2.5-upgrade
      import: app/west.yml
  self:
    path: config
